version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend-flask 
      - backend-express
      - frontend

  backend-flask:
    build:
      context: backend-flask
      dockerfile: Dockerfile
    command: flask --debug --app app.wsgi run --port 5000 --host 0.0.0.0
    ports:
      - 5000:5000
    tty: true
    volumes:
      - type: bind
        source: ./backend-flask
        target: /app/
    environment:
      PYTHONPATH: .
  
  backend-express:
    build:
      context: backend-express
      dockerfile: Dockerfile
    command: npm start 
    stdin_open: true
    ports:
      - 5001:5001
    volumes:
      - type: bind 
        source: ./backend-express
        target: /app
    environment:
      - NODE_ENV=development


  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm start
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - type: bind 
        source: ./frontend
        target: /app
    environment:
      - NODE_ENV=development
